### ISSUE TITLE
[feature request] Add power toggle, monitor out and display brightness commands

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/integration-denonavr#37]
### Description

It would be nice if the following commands could be added to this integration:

- Power Toggle (currently there are only separate commands for on/off)
- Monitor Out (separate commands for auto, 1, 2 etc.)
- Display Brightness (separate commands for off, bright, dim, dark, toggle)

**Comment by zehnm** [comment]
The remaining commands should be pretty straightforward to implement, based on the monitor out contribution from @splattner 
Telnet commands:
<img width="660" alt="image" src="https://github.com/unfoldedcircle/integration-denonavr/assets/17356629/959eb999-bc8a-41eb-a2e8-4e817ffaf5a1">

I'm not aware of a native power toggle, but will check again. Otherwise this can be implemented in the driver.

**Comment by zehnm** [comment]
If started implementing the missing commands and try to squeeze it in today's planned beta-firmware release.
